<?php
/**
 * Terms and Conditions - MakeAIBucks
 */
require_once '../includes/config.php';

$SEO_DATA = [
    'title' => 'Terms of Service — MakeAIBucks',
    'description' => 'Rules and guidelines for using our AI tools.'
];

include '../includes/header.php';
?>

<div class="bg-bg-page min-h-screen py-24">
    <main class="max-w-4xl mx-auto px-6">
        <h1 class="text-4xl md:text-6xl font-black text-slate-900 mb-12 tracking-tighter">Terms of Service</h1>
        
        <div class="bg-white rounded-[40px] p-10 md:p-16 shadow-sm border border-slate-200">
            <div class="prose prose-slate prose-lg max-w-none text-slate-600 font-medium leading-relaxed space-y-10">
                <section>
                    <h2 class="text-2xl font-black text-slate-900 mb-4">1. Acceptance</h2>
                    <p>By using MakeAIBucks, you agree to these terms. Our tools are provided "as-is" for experimental and productivity purposes.</p>
                </section>

                <section>
                    <h2 class="text-2xl font-black text-slate-900 mb-4">2. Commercial Use</h2>
                    <p>You own the output content generated by the AI tools for your specific inputs. You are free to use them for your business, Fiverr gigs, or marketing. However, we do not guarantee the accuracy or legal safety of generated AI content.</p>
                </section>

                <section>
                    <h2 class="text-2xl font-black text-slate-900 mb-4">3. Prohibited Use</h2>
                    <p>You may not use our tools to generate illegal, harmful, or spam content. Botting or automated scraping of our AI endpoints is strictly prohibited and will result in IP banning.</p>
                </section>

                <section>
                    <h2 class="text-2xl font-black text-slate-900 mb-4">4. Limitation of Liability</h2>
                    <p>MakeAIBucks is not liable for any business losses, technical failures, or inaccuracies in the AI-generated results.</p>
                </section>
            </div>
        </div>
    </main>
</div>

<?php include '../includes/footer.php'; ?>
